# Generated by Django 2.2 on 2019-09-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0005_auto_20190914_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='eventFinderApp.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
